### ISSUE TITLE
Cannot initialize OnePlus/9.0.0 branch repo

### ISSUE THREAD

**Issue by lakgarg** [OnePlusOSS/android#41]
While initialising OnePlus/9.0.0 branch repo, am getting an error " manifest 'default.xml' not available"

**Comment by piet-delaney** [comment]
Yep, I've dealing with the same problem. The problem with the default.xml is that the
definition of the remote 'onepus' seems to be missing.

**Comment by TeamFahQ** [comment]
Please fix oneplus

**Comment by lakgarg** [comment]
OxygenOS isn't open source.

**Comment by TeamFahQ** [comment]
It seems to be according to this
[https://forums.oneplus.com/threads/oxygenos-is-now-open-source.449198/](url)
It's actually easy enough to edit the default.xml and define oneplus with the correct path. But once I did that, it opened up another issue with several other repos
[https://hastebin.com/xisekodaha.coffeescript](url)
This is because of the following
`  <remote fetch="ssh://jyg@grease-china.qualcomm.com:29418/" name="grease" review="grease-china.qualcomm.com"/>`
This is the part that makes things difficult as this is NOT open source, and to make matters worse, there is no equivalent for those repos in the codeaurora open source trees.
